Remove: l10n_do_purchase, l10n_do_sale,l10n_do_account_cancel, add so…
raulovallet/l10n-dominicana-pro pull request #2
Opened 2023-02-18 07:54 UTC by jorgeh45

…me change to the report, fix problem with invoice email

2023-02-18 18:57 UTC, raulovallet commented
@jorgeh45 intente de cancelar la factura y no sale el popup del motivo de la cancelación

2023-02-18 18:59 UTC, raulovallet requested changes
Intente de cancelar la factura y no sale el popup de cancelación

2023-02-24 05:03 UTC, jorgeh45 commented
Ya agregue la parte de la cancelacion

2023-03-03 02:37 UTC, raulovallet approved these changes
bien

2023-03-03 02:37 UTC, merged